# This file is autogenerated by running
#  ./make-spec.sh droid-bin-hammerhead.spec
# Please edit droid-bin-hammerhead.spec.tmpl and re-run that command to modify

# device is the codename for the device
# eg mako = Nexus 4
%define device hammerhead

# vendor is used in device/%vendor/%device/
%define vendor lge

# Manufacturer and device name to be shown in UI
%define vendor_pretty LG
%define device_pretty Nexus 5

# repo service performed : %%include define-trees
%define dbd_src_trees abi bionic bootable build device external frameworks hardware libcore libnativehelper kernel prebuilts/clang/linux-x86 prebuilts/gcc/linux-x86 prebuilts/misc prebuilts/ndk prebuilts/sdk prebuilts/tools system vendor

%define dbd_sources \
Source52: droid-bin-%{?ha_device_override}%{!?ha_device_override:%{device}}.spec.tmpl\
%{nil}

# repo service performed : %%include droid-bin-device.inc
# This file should be %%included into a device specific spec file
# where macros are defined:
# device: should be the CM codename or the AOSP TARGET_PRODUCT
# vendor: determine the directory used for ./device/<vendor>/<device>
# device_pretty: User-visible model name of the device
# vendor_pretty: User-visible manufacturer name of the device
# hadk_make_target: the target used when running make in the HABUILD_SDK on the OBS. Defaults to "hybris-hal"
# device_target_cpu: Used for native builds. Normally the nested droid build env will do an old-fashioned cross-compile and produce non-x86 binaries (default armv7hl). This can be set to tell OBS what arch the binaries are. Eg Android for Intel arch must set this.
# device_variant: for AOSP this is used as the TARGET_BUILD_VARIANT for lunch

%define __provides_exclude_from ^%{_libexecdir}/droid-hybris/.*$
%define android_root .

%define __find_provides %{nil}
%define __find_requires %{nil}
%define __strip /bin/true
%define __provides_exclude_from ^/system/.*$
%define __requires_exclude ^.*$
%global debug_package %{nil}

# On the OBS this package should be built in the i486 scheduler against
# mer/sailfish *_i486 targets.
# The prjconf should have an ExportFilter like this (mer/sailfish has this):
#   ExportFilter: \.armv7hl\.rpm$ armv8el
# We lie about our architecture and allows OBS to cross-publish this 486 cross-built spec to the armv7hl repos
%if 0%{?device_target_cpu:1}
%define _target_cpu %{device_target_cpu}
%else
%define _target_cpu armv7hl
%endif

# Support build info extracted from OBS builds too
%if 0%{?_obs_build_project:1}
%define _build_flavour %(echo %{_obs_build_project} | awk -F : '{if ($NF == "testing" || $NF == "release") print $NF; else if ($NF ~ /[0-9]\.[0-9]\.[0-9]/ && NF == 3) print strdevel; else if (NF == 2) print strdevel; else print strunknown}' strdevel=devel strunknown=unknown)
%else
%define _build_flavour unknown
%endif

%define _obs_build_count %(echo %{release} | awk -F . '{if (NF >= 3) print $3; else print $1 }')
%define _obs_commit_count %(echo %{release} | awk -F . '{if (NF >= 2) print $2; else print $1 }')

%if "%{_build_flavour}" == "release"
%define _version_appendix (%{_target_cpu})
%else
%define _version_appendix (%{_target_cpu},%{_build_flavour})
%endif

%if 0%{?ha_device_override:1}
%define ha_device %{ha_device_override}
%else
%define ha_device %{device}
%endif

# Don't run strip
%define __strip /bin/true

Summary: 	Droid BIN package for %{ha_device}
License: 	BSD-3-Clause
Name: 		droid-bin-%{ha_device}
Version: 	0.0.6
# timestamped releases are used only for HADK (mb2) builds
%if 0%{?_obs_build_project:1}
Release:	1
%else
Release:	%(date +'%%Y%%m%%d%%H%%M')
%endif
Provides:	droid-bin
# The repo sync service on OBS prepares a 'source tarball' of the rpm
# dir since we currently have a complex setup with subdirs which OBS
# doesn't like. This is not a problem for local builds.
Source0: 	rpm.tar.bzip2
Source10:       droid-bin-device.inc
# Ths actual droid source from the repo service when run on OBS.
# local builds don't mind if this is missing
Source40:       repo.tar.bzip2
Source41:       make-spec.sh
# Reserve Source50 onwards
# Allow device specific sources to be defined using dbd_sources
%{?dbd_sources}

Group:		System

%description
%{summary}.

%if 0%{?dbd_src_trees:1}
# repo service performed : %%include package-section
%package src-full
Provides: droid-bin-src-full
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Requires:  droid-bin-src-abi, droid-bin-src-bionic, droid-bin-src-bootable, droid-bin-src-build, droid-bin-src-device, droid-bin-src-external, droid-bin-src-frameworks, droid-bin-src-hardware, droid-bin-src-libcore, droid-bin-src-libnativehelper, droid-bin-src-kernel, droid-bin-src-prebuilts-clang-linux-x86, droid-bin-src-prebuilts-gcc-linux-x86, droid-bin-src-prebuilts-misc, droid-bin-src-prebuilts-ndk, droid-bin-src-prebuilts-sdk, droid-bin-src-prebuilts-tools, droid-bin-src-system, droid-bin-src-vendor
Summary: Syspart source for all the  src trees to be used for droid-side code building

%description src-full
This is the full src tree for the %device syspart manifest.
It is only meant for use in the OBS.

%package srcutils
Provides: droid-bin-srcutils
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Utilities for droid-side code building for %{device}%{?device_variant}

%description srcutils
Summary: Utilities for using the syspart source for droid-side code building.
This package is hardcoded for %{device}%{?device_variant}
It is only meant for use in the OBS.

%package src-makefile
Provides: droid-bin-src-makefile
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Syspart top level makefile to be used for droid-side code building

%description src-makefile
Syspart top level makefile to be used for droid-side code building
It is only meant for use in the OBS.


%package src-abi
Provides: droid-bin-src-abi
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the abi src tree to be used for droid-side code building

%description src-abi
This is the src tree for the abi subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-bionic
Provides: droid-bin-src-bionic
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the bionic src tree to be used for droid-side code building

%description src-bionic
This is the src tree for the bionic subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-bootable
Provides: droid-bin-src-bootable
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the bootable src tree to be used for droid-side code building

%description src-bootable
This is the src tree for the bootable subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-build
Provides: droid-bin-src-build
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the build src tree to be used for droid-side code building

%description src-build
This is the src tree for the build subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-device
Provides: droid-bin-src-device
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the device src tree to be used for droid-side code building

%description src-device
This is the src tree for the device subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-external
Provides: droid-bin-src-external
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the external src tree to be used for droid-side code building

%description src-external
This is the src tree for the external subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-frameworks
Provides: droid-bin-src-frameworks
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the frameworks src tree to be used for droid-side code building

%description src-frameworks
This is the src tree for the frameworks subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-hardware
Provides: droid-bin-src-hardware
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the hardware src tree to be used for droid-side code building

%description src-hardware
This is the src tree for the hardware subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-libcore
Provides: droid-bin-src-libcore
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the libcore src tree to be used for droid-side code building

%description src-libcore
This is the src tree for the libcore subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-libnativehelper
Provides: droid-bin-src-libnativehelper
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the libnativehelper src tree to be used for droid-side code building

%description src-libnativehelper
This is the src tree for the libnativehelper subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-kernel
Provides: droid-bin-src-kernel
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the kernel src tree to be used for droid-side code building

%description src-kernel
This is the src tree for the kernel subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-clang-linux-x86
Provides: droid-bin-src-prebuilts-clang-linux-x86
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-clang-linux-x86 src tree to be used for droid-side code building

%description src-prebuilts-clang-linux-x86
This is the src tree for the prebuilts-clang-linux-x86 subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-gcc-linux-x86
Provides: droid-bin-src-prebuilts-gcc-linux-x86
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-gcc-linux-x86 src tree to be used for droid-side code building

%description src-prebuilts-gcc-linux-x86
This is the src tree for the prebuilts-gcc-linux-x86 subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-misc
Provides: droid-bin-src-prebuilts-misc
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-misc src tree to be used for droid-side code building

%description src-prebuilts-misc
This is the src tree for the prebuilts-misc subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-ndk
Provides: droid-bin-src-prebuilts-ndk
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-ndk src tree to be used for droid-side code building

%description src-prebuilts-ndk
This is the src tree for the prebuilts-ndk subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-sdk
Provides: droid-bin-src-prebuilts-sdk
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-sdk src tree to be used for droid-side code building

%description src-prebuilts-sdk
This is the src tree for the prebuilts-sdk subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-prebuilts-tools
Provides: droid-bin-src-prebuilts-tools
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the prebuilts-tools src tree to be used for droid-side code building

%description src-prebuilts-tools
This is the src tree for the prebuilts-tools subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-system
Provides: droid-bin-src-system
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the system src tree to be used for droid-side code building

%description src-system
This is the src tree for the system subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.


%package src-vendor
Provides: droid-bin-src-vendor
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the vendor src tree to be used for droid-side code building

%description src-vendor
This is the src tree for the vendor subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.

%endif

%prep
# No %%setup macro !!

%if 0%{?_obs_build_project:1}
# The OBS does not have access to 'repo' so a service does the repo init/sync
# and provides a (huge) tarball with the checked-out tree in it.
# So now drop to android_root and pretend to do a repo sync
tar xf %{SOURCE40} -C %android_root
# Clean up the repo tarball to save space
rm -f %{SOURCE40}
# Make a dummy tarball for rpm checks
mkdir dummy;(cd dummy; touch dummy; tar cvf - . | bzip2 > %{SOURCE40}); rm -rf dummy
# unpack the directories to SOURCES ... this needs to change
tar xf %{SOURCE0} -C ../SOURCES
# Clean up the rpm tarball too
rm -f %{SOURCE0}
cp %{SOURCE40} %{SOURCE0}

# In OBS the repo service leaves the rpm/* files for OBS and they just ^^
# got unpacked to ../SOURCES ... but we're used to having an rpm/ dir
# So if rpm/ is missing then we use ../SOURCES :
[ -d rpm ] || ln -s ../SOURCES rpm
%endif

%build

echo _target_cpu is %{_target_cpu}

# We'll hardcode the device/variant information into the droid-make
# script This isn't trivially installable into the ubu-chroot so
# include the ubu-chroot command within it
cat <<"EOF" > droid-make
#!/bin/bash

# This command runs a hardware-specific 'make' command inside the
# ubu-chroot with the correct lunch setup
# It is only intended to run in the OBS builders

exec ubu-chroot -r /srv/mer/sdks/ubu "source build/envsetup.sh; lunch %{device}%{?device_variant}; make $*"
EOF

################
%install
rm -rf $RPM_BUILD_ROOT

# Support the building of src-* rpms and srcutils if they're wanted
%if 0%{?dbd_src_trees:1}
# To create a set of rpms that hold the *source* we move the subset of
# src to the buildroot for packaging
# These will be used to create buildroots for packages like droidmedia
mkdir -p $RPM_BUILD_ROOT/home/abuild/src/droid
for tree in %dbd_src_trees ; do
   d=$(dirname $tree)
   mkdir -p $RPM_BUILD_ROOT/home/abuild/src/droid/$d
   mv %android_root/$tree $RPM_BUILD_ROOT/home/abuild/src/droid/$d
done

# Top level makefile
mv %android_root/Makefile $RPM_BUILD_ROOT/home/abuild/src/droid/

# Install the droid-make helper
mkdir -p $RPM_BUILD_ROOT/usr/bin
cp droid-make $RPM_BUILD_ROOT/usr/bin

%endif

################################################################
# Begin files section

#files
#defattr(-,root,root,-)

%if 0%{?dbd_src_trees:1}
# repo service performed : %%include files-section
%files src-full
# Deliberately empty

%files srcutils
%defattr(755,root,root,-)
/usr/bin/droid-make

%post src-makefile
# The abuild user is not setup at post time so we use the numeric id
chown 399:399 /home/abuild/src
chown 399:399 /home/abuild/src/droid
chown 399:399 /home/abuild/src/droid/Makefile

%files src-makefile
%defattr(-,root,root,-)
/home/abuild/src/droid/Makefile
%post src-abi
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/abi

%files src-abi
%defattr(-,root,root,-)
/home/abuild/src/droid/abi
%post src-bionic
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/bionic

%files src-bionic
%defattr(-,root,root,-)
/home/abuild/src/droid/bionic
%post src-bootable
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/bootable

%files src-bootable
%defattr(-,root,root,-)
/home/abuild/src/droid/bootable
%post src-build
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/build

%files src-build
%defattr(-,root,root,-)
/home/abuild/src/droid/build
%post src-device
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/device

%files src-device
%defattr(-,root,root,-)
/home/abuild/src/droid/device
%post src-external
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/external

%files src-external
%defattr(-,root,root,-)
/home/abuild/src/droid/external
%post src-frameworks
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/frameworks

%files src-frameworks
%defattr(-,root,root,-)
/home/abuild/src/droid/frameworks
%post src-hardware
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/hardware

%files src-hardware
%defattr(-,root,root,-)
/home/abuild/src/droid/hardware
%post src-libcore
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/libcore

%files src-libcore
%defattr(-,root,root,-)
/home/abuild/src/droid/libcore
%post src-libnativehelper
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/libnativehelper

%files src-libnativehelper
%defattr(-,root,root,-)
/home/abuild/src/droid/libnativehelper
%post src-kernel
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/kernel

%files src-kernel
%defattr(-,root,root,-)
/home/abuild/src/droid/kernel
%post src-prebuilts-clang-linux-x86
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/clang/linux-x86

%files src-prebuilts-clang-linux-x86
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/clang/linux-x86
%post src-prebuilts-gcc-linux-x86
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/gcc/linux-x86

%files src-prebuilts-gcc-linux-x86
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/gcc/linux-x86
%post src-prebuilts-misc
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/misc

%files src-prebuilts-misc
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/misc
%post src-prebuilts-ndk
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/ndk

%files src-prebuilts-ndk
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/ndk
%post src-prebuilts-sdk
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/sdk

%files src-prebuilts-sdk
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/sdk
%post src-prebuilts-tools
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/prebuilts/tools

%files src-prebuilts-tools
%defattr(-,root,root,-)
/home/abuild/src/droid/prebuilts/tools
%post src-system
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/system

%files src-system
%defattr(-,root,root,-)
/home/abuild/src/droid/system
%post src-vendor
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/vendor

%files src-vendor
%defattr(-,root,root,-)
/home/abuild/src/droid/vendor
%endif
