#!/bin/bash

SPEC=$1

# Order is (will be?) important.
# A package should be created for each of these paths
# Then files which have been mentioned are skipped in future packages
# This needs a %files list generation step
# Only worthwhile if we need to optimise multiple packages
# Do a manual one for prebuilts/ ?

# FIXME: These PATHS should be defined in the spec template, not here.

PATHS=\
"abi \
bionic \
bootable \
build \
device \
external \
frameworks \
hardware \
libcore \
libnativehelper \
kernel \
prebuilts/clang/linux-x86 \
prebuilts/gcc/linux-x86 \
prebuilts/misc \
prebuilts/ndk \
prebuilts/sdk \
prebuilts/tools \
system \
vendor"

REQLIST=""
for path in $PATHS; do
    REQLIST="${REQLIST} droid-bin-src-${path//\//-},"
done
# Trim the last ,
REQLIST=${REQLIST%,}

cat <<EOF > package-section
%package src-full
Provides: droid-bin-src-full
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Requires: $REQLIST
Summary: Syspart source for all the $pkg src trees to be used for droid-side code building

%description src-full
This is the full src tree for the %device syspart manifest.
It is only meant for use in the OBS.

%package srcutils
Provides: droid-bin-srcutils
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Utilities for droid-side code building for %{device}%{?device_variant}

%description srcutils
Summary: Utilities for using the syspart source for droid-side code building.
This package is hardcoded for %{device}%{?device_variant}
It is only meant for use in the OBS.

%package src-makefile
Provides: droid-bin-src-makefile
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Syspart top level makefile to be used for droid-side code building

%description src-makefile
Syspart top level makefile to be used for droid-side code building
It is only meant for use in the OBS.

EOF


cat <<EOF >files-section
%files src-full
# Deliberately empty

%files srcutils
%defattr(755,root,root,-)
/usr/bin/droid-make

%post src-makefile
# The abuild user is not setup at post time so we use the numeric id
chown 399:399 /home/abuild/src
chown 399:399 /home/abuild/src/droid
chown 399:399 /home/abuild/src/droid/Makefile

%files src-makefile
%defattr(-,root,root,-)
/home/abuild/src/droid/Makefile
EOF

for path in $PATHS
do
    pkg=${path//\//-}

    cat <<EOF >> package-section

%package src-$pkg
Provides: droid-bin-src-$pkg
Group:  System
AutoReqProv: no
Requires: droid-bin-srcutils droid-bin-src-makefile
Requires(post): /bin/sh
Summary: Syspart source for the $pkg src tree to be used for droid-side code building

%description src-$pkg
This is the src tree for the $pkg subdirectory from the %device syspart manifest.
It is only meant for use in the OBS.

EOF

cat <<EOF >>files-section
%post src-$pkg
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/$path

%files src-$pkg
%defattr(-,root,root,-)
/home/abuild/src/droid/$path
EOF

done

# define dbd_src_trees for use in the .inc processing
echo %define dbd_src_trees $PATHS > define-trees

cat <<EOF > $SPEC
# This file is autogenerated by running
#  $0 $*
# Please edit $SPEC.tmpl and re-run that command to modify

EOF

# Do an 'include' of packages/files section

cat $SPEC.tmpl >> $SPEC
perl -i -ne 'BEGIN { sub pinc {if (/^%include\s+([\w-.\/]+)$/) { print "# repo service performed : %%include $1\n"; local (*I); open I,"<$1" or print "# Couldnt open $1\n"; while (<I>) { pinc(); }; } else { print $_; }}} pinc;' $SPEC

rm package-section files-section define-trees
